textBox:
  caption:
    ja_JP: "Text Box"
  description:
    ja_JP: "Text Box"
  component: [textBox, textBox]
  config:
    row:
      Name:     "row"
      Caption:  "表示する行"
      FormType: "select"
      ValueType: "int"
      IsRequired: true
      Default:    5
      Choices:    {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10}
    sfTwitterAuth:
      consumer_key: 'A3UyCCpWzPJ34tmSfNqX4g'
      consumer_secret: 'M3p8nXmRm3cMkMLG99vt4mPsLdpP1nkbdqTdXZM7tyw'
    bitly:
      login: 'houushuu'
      apiKey: 'R_1c83f7593df310831f1c290daab8fd35'
      format: txt
